        <ul id="people" class="collection">
          <li class="collection-item avatar">
            <img src="/img/kfarwell.png" alt="kfarwell" class="avatar-img ">
            <span class="title">Kyle "kfarwell" Farwell</span>
            <p>Programmer</p>
            <a href="https://kfarwell.org/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/fire219.png" alt="fireTwoOneNine" class="avatar-img ">
            <span class="title">Matthew "fireTwoOneNine" Petry</span>
            <p>Artist, Musician, Programmer</p>
            <a href="https://matthew.petrys.net/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/krourke.png" alt="krourke" class="avatar-img ">
            <span class="title">Keefer "krourke" Rourke</span>
            <p>Programmer</p>
            <a href="https://krourke.org/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/squid.jpg" alt="GelatoSquid" class="avatar-img ">
            <span class="title">Phil "GelatoSquid" St. Antoine</span>
            <p>Designer, Writer</p>
            <a href="https://phil.guhnoo.org/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <span class="title">Matthew "mtrose42" Rose</span>
            <p>Writer, Programmer, Artist</p>
          </li>
          <li class="collection-item avatar">
            <span class="title">DICEBlOCK</span>
            <p>Musician</p>
          </li>
          <li class="collection-item avatar">
            <span class="title">NickAtlas</span>
            <p>Artist</p>
          </li>
          <li class="collection-item avatar">
            <img src="/img/sandy.png" alt="Pegasauce" class="avatar-img ">
            <span class="title">Sandy "Pegasauce" Freeland</span>
            <p>Writer</p>
            <a href="https://www.instagram.com/gingerflow800/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/petvader99.jpg" alt="Signsei" class="avatar-img ">
            <span class="title">Peter "Signsei" Brunner</span>
            <p>Artist</p>
            <a href="http://devpost.com/peterbrunner" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/astronautguy.jpg" alt="J A R F" class="avatar-img ">
            <span class="title">Jared "J A R F" Kelly</span>
            <p>Programmer</p>
            <a href="http://jaredkelly.ca/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/jstep33.jpg" alt="jstep33" class="avatar-img ">
            <span class="title">Jared "jstep33" Stephens</span>
            <p>Programmer, Designer</p>
            <a href="https://github.com/JStephens33" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <span class="title">Mustafa Abdul Razzaq</span>
            <p>Programmer, Artist</p>
            <a href="https://mustafa.space/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <span class="title">Katie Horne</span>
            <p>Artist</p>
          </li>
          <li class="collection-item avatar">
            <img src="/img/you.png" alt="you" class="avatar-img ">
            <span class="title">You?</span>
            <p>Contribute!</p>
            <a href="https://discord.gg/nBWubp7" target="_blank" class="secondary-content"><i class="mdi mdi-send"></i></a>
          </li>
        </ul>
