        <ul id="people" class="collection">
          <li class="collection-item avatar">
            <img src="/img/kfarwell.png" alt="kfarwell" class="avatar-img">
            <span class="title">Kyle "kfarwell" Farwell</span>
            <p>Programmer</p>
            <a href="https://kfarwell.org/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/fire219.png" alt="fireTwoOneNine" class="avatar-img">
            <span class="title">Matthew "fireTwoOneNine" Petry</span>
            <p>Artist, Musician, Programmer</p>
            <a href="http://fire219.github.io" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/matt.png" alt="MTRooster" class="avatar-img">
            <span class="title">Matt "MTRooster" Rose</span>
            <p>Writer, Programmer, Artist</p>
            <a href="https://live.staticflickr.com/8507/8374802487_3d1b775a34_b.jpg" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/krourke.png" alt="krourke" class="avatar-img">
            <span class="title">Keefer "krourke" Rourke</span>
            <p>Programmer</p>
            <a href="https://krourke.org/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/aliciana.png" alt="aliciana" class="avatar-img">
            <span class="title">Alice "Aliciana" Dalton</span>
            <p>Musician</p>
            <a href="https://soundcloud.com/notanarchy" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/rrefcio.jpg" alt="rrefcio" class="avatar-img">
            <span class="title">Ryan Refcio</span>
            <p>Designer, Writer</p>
          </li>
          <li class="collection-item avatar">
            <span class="title">DICEBlOCK</span>
            <p>Musician</p>
          </li>
          <li class="collection-item avatar">
            <img src="/img/nickatlas.jpg" alt="NickAtlas" class="avatar-img">
            <span class="title">NickAtlas</span>
            <p>Artist</p>
            <a href="https://www.instagram.com/reality_simulator/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/sandy.png" alt="Pegasauce" class="avatar-img">
            <span class="title">Sandy "Pegasauce" Freeland</span>
            <p>Writer</p>
            <a href="https://www.instagram.com/gingerflow800/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/petvader99.jpg" alt="Signsei" class="avatar-img">
            <span class="title">Peter "Signsei" Brunner</span>
            <p>Artist</p>
            <a href="http://devpost.com/peterbrunner" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/astronautguy.jpg" alt="J A R F" class="avatar-img">
            <span class="title">Jared "J A R F" Kelly</span>
            <p>Programmer</p>
            <a href="http://jaredkelly.ca/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/jstep33.jpg" alt="jstep33" class="avatar-img">
            <span class="title">Jared "jstep33" Stephens</span>
            <p>Programmer, Designer</p>
            <a href="https://github.com/JStephens33" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <img src="/img/mustafa.jpg" alt="mustafa" class="avatar-img">
            <span class="title">Mustafa Abdul Razaq</span>
            <p>Programmer, Artist</p>
            <a href="https://mustafa.space/" target="_blank" class="secondary-content"><i class="mdi mdi-web"></i></a>
          </li>
          <li class="collection-item avatar">
            <span class="title">Katie Horne</span>
            <p>Artist</p>
          </li>
          <li class="collection-item avatar">
            <img src="/img/you.png" alt="you" class="avatar-img">
            <span class="title">You?</span>
            <p>Contribute!</p>
            <a href="https://discord.gg/nBWubp7" target="_blank" class="secondary-content"><i class="mdi mdi-send"></i></a>
          </li>
        </ul>
